allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  dc94ff99-3bba-4564-a499-db632c813a1b:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e19d1e17-c887-42cd-9b66-14558456cc62 # Eyebrow
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e518d1e-9447-421f-8df9-70ba5119c970
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7ac39a8f-9250-4234-acfc-12fc4642e5cb # Heading
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a34577d-27b0-43ac-971e-cb1c1886b652
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6e72687a-a30e-46cb-bd37-c39eece0b6d4 # Body Copy
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 962304c6-88ce-424c-8ca9-e9e6c1c6bdf9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4b41a6fa-be67-47e5-9b98-c4618547c8e1
        userCondition: null
    thumbFieldKey: null
handle: contentSection
hasTitleField: false
icon: null
name: 'Content Section'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{heading}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{heading}'
