allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  f701c0ed-1c52-404a-aad4-b7d769f5b2f9:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 497175e2-bed5-41f2-932e-c59e2d318201 # Icon
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5f5ccaa-631b-4161-ba76-023b21dd377e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7ac39a8f-9250-4234-acfc-12fc4642e5cb # Heading
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b72442dd-9d3c-4a7a-a0e1-ac8847b9c95b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0c96b99e-876d-42fb-9783-09f02e856dc1 # Body
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb74ebcf-b067-4b15-8e6d-ec001c6eb064
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b3e00c20-78de-4496-853f-f4ca67a063b7 # Link
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c543a51a-2fe1-4ccd-8e91-bb2146bd5d3a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3b239d1d-f5b5-473b-8860-3bef5fbbe42c
        userCondition: null
    thumbFieldKey: null
handle: gridItem
hasTitleField: false
icon: null
name: 'Grid Item'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{heading}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{heading}'
