allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  b9ca62ea-4b67-4153-a5f1-584ccfe11c45:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e19d1e17-c887-42cd-9b66-14558456cc62 # Eyebrow
            handle: null
            instructions: 'For example, Step 1.'
            label: 'Step Label'
            oldFieldUid: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 010c6b3c-635c-4cfd-ae4f-c71d76c3761f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7ac39a8f-9250-4234-acfc-12fc4642e5cb # Heading
            handle: null
            instructions: null
            label: 'Step Heading'
            oldFieldUid: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c16c84e6-a0ab-4b85-8ef6-aa8641639184
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6e72687a-a30e-46cb-bd37-c39eece0b6d4 # Body Copy
            handle: null
            instructions: null
            label: 'Step Copy'
            oldFieldUid: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db9e3e78-ae98-4d8f-b222-c5016fcf1e5b
            userCondition: null
            warning: null
            width: 100
        name: Step
        uid: 5dc6df47-7748-4fb4-b76a-8cf67a1c1cfd
        userCondition: null
    thumbFieldKey: null
handle: howItWorksStep
hasTitleField: false
icon: null
name: 'How It Works Step'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{eyebrow}: {heading}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{eyebrow}: {heading}'
