allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  4a1a5d93-f6a5-4ace-a0b5-88cf687f3c17:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-09-30T21:31:34+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ba64a604-acde-4d7d-86fe-bdff95c950b8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-30T21:31:34+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 43f4f99f-df7a-4b4b-9b73-6631202cb847 # Index Image
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28d840cb-b9a1-484f-b330-e0bd0745dfd3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e0b08c73-6245-447a-bac7-1b68557a1f74
        userCondition: null
    thumbFieldKey: null
handle: indexPage
hasTitleField: true
icon: null
name: 'Index Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
