columnSuffix: null
handle: homeLogos
instructions: 'Add logos in the order they should appear on the homepage.'
name: 'Home Logos'
searchable: false
settings:
  createButtonLabel: 'Add logo'
  defaultIndexViewMode: cards
  enableVersioning: true
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 6fea538f-dbb9-499f-8901-8d59d0815125 # Home Logo
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
