columnSuffix: null
handle: logoImage
instructions: 'Upload a clear logo with a transparent background when possible.'
name: 'Logo Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:57893d02-3fec-449e-a138-957e9323d2a1' # Photos
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  previewMode: full
  restrictFiles: false
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:57893d02-3fec-449e-a138-957e9323d2a1' # Photos
  restrictedLocationSubpath: null
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:57893d02-3fec-449e-a138-957e9323d2a1' # Photos
  targetSiteId: null
  validateRelatedElements: false
  viewMode: thumbs
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
