fieldLayouts:
  2949819c-2f37-4f1e-b07c-8bbf0f2b9c4b:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 43685cdd-cfb6-48c5-b3b8-2b11def1ad07 # Grid
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8583eb87-982e-4bc2-b36c-85310b86dac7
            userCondition: null
            warning: null
            width: 100
        name: Grid
        uid: a28674ac-0f22-4f47-9ef3-696fb2024ad5
        userCondition: null
    thumbFieldKey: null
handle: grid
name: Grid
sortOrder: 1
