defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 937f197b-670d-40ec-8b51-8cccdcef54ea # Advertiser
handle: advertisers
maxAuthors: 1
minAuthors: 1
name: Advertisers
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  4697f176-6bfa-4a98-85e5-a7b83e25d7bc: # adspot
    enabledByDefault: true
    hasUrls: true
    template: advertisers/_entry.twig
    uriFormat: 'advertisers/{slug}'
structure:
  maxLevels: null
  uid: 6239d932-6d5a-4b9a-9f74-fe67b3e47705
type: structure
