defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 8f52b621-39cc-48d2-b870-890301665097 # Index Page
handle: blogIndex
maxAuthors: 1
minAuthors: 1
name: 'Blog Index'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  4697f176-6bfa-4a98-85e5-a7b83e25d7bc: # adspot
    enabledByDefault: true
    hasUrls: true
    template: blog/index.twig
    uriFormat: blog
type: single
