defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: db8196f1-344f-4ba0-86ab-bd52b54b7900 # Home Page
handle: home
maxAuthors: 1
minAuthors: 1
name: Home
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  4697f176-6bfa-4a98-85e5-a7b83e25d7bc: # adspot
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
